name: Jekyll site CI

on:
  push:
    branches: [ "pages" ]
  pull_request:
    branches: [ "pages" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Jekyll Actions
      uses: helaili/jekyll-action@2.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
